# Rex Lei rexlei86@uvic.ca
# parse the coordinates data from the file generated by leapmotion

import sys, glob, os,csv

def parser2(filename):
	raw = open(filename)
	fbname = filename.split('.')[0]
	pfile = open("../"+fbname+".txt", "w")
	pFre = open("../statistics/"+fbname+"Stat.txt", "w")
	csvFp = csv.writer(open("../"+fbname+".csv", 'w'))
	freqency = [0,0,0,0,0]
	rowlines = []

	for line in raw:
		if len(line) > 2:
			if line[:2] == "fx":
				rowlines.append(line)
			elif line[:2] == "**":
				rowlinesLen = len(rowlines)
				if rowlinesLen == 1:
					freqency[0] = freqency[0] + 1
				if rowlinesLen == 2:
					freqency[1] = freqency[1] + 1
				if rowlinesLen == 3:
					freqency[2] = freqency[2] + 1
				if rowlinesLen == 4:
					freqency[3] = freqency[3] + 1
				if rowlinesLen == 5:
					freqency[4] = freqency[4] + 1

				x,y,z = rowlines[0].split('\t')
				x = x[3:]
				y = y[3:]
				z = z[3:]
				rowlines = []
			 	# print x+" "+y+" "+z
			 	pfile.write(x+" "+y+" "+z)
			 	csvFp.writerow([x,y,z])

	raw.close()
	pfile.close()
	pFre.write(', '.join(map(str, freqency)))
	print freqency
	pFre.close()

def parser(filename):
	raw = open(filename)
	fbname = filename.split('.')[0]
	pfile = open("../"+fbname+"Parsed.txt", "w")

	for line in raw:
		if len(line) > 2:
			if line[:2] == "fx":
				x,y,z = line.split('\t')
				x = x[3:]
				y = y[3:]
				z = z[3:]
			 	# print x+" "+y+" "+z
			 	pfile.write(x+" "+y+" "+z)

	raw.close()
	pfile.close()

def scanFiles(directory):
	fList = []
	os.chdir(directory)
	for filename in glob.glob("*.txt"):
	    print filename
	    fList.append(filename)

	return fList

def main():
	# parser(sys.argv[1])
	fList = scanFiles(sys.argv[1])
	for filename in fList:
		parser2(filename)

if __name__ == '__main__':
	main()