# Rex Lei rexlei86@uvic.ca
# parse the coordinates data from the file generated by leapmotion

import sys, glob, os

def parser(filename):
	raw = open(filename)
	fbname = filename.split('.')[0]
	pfile = open("../"+fbname+"Parsed.txt", "w")

	for line in raw:
		if len(line) > 2:
			if line[:2] == "fx":
				x,y,z = line.split('\t')
				x = x[3:]
				y = y[3:]
				z = z[3:]
			 	# print x+" "+y+" "+z
			 	pfile.write(x+" "+y+" "+z)

	raw.close()
	pfile.close()

def scanFiles(directory):
	fList = []
	os.chdir(directory)
	for filename in glob.glob("*.txt"):
	    print filename
	    fList.append(filename)

	return fList

def main():
	# parser(sys.argv[1])
	fList = scanFiles(sys.argv[1])
	for filename in fList:
		parser(filename)

if __name__ == '__main__':
	main()